### ISSUE TITLE
The problems that arise with Shady and WALL-E 

### ISSUE THREAD

**Issue by lespygaming** [PRISM-Servers/plugins_public#1]
The issue consists of Shady (the server owner and contributor of these plugins) not endulging in watching a movie called WALL-E (2009), that is a 2008 American animated science fiction film produced by Pixar Animation Studios for Walt Disney Pictures. The film was directed by Andrew Stanton, produced by Jim Morris, and written by Stanton and Jim Reardon. It stars the voices of Ben Burtt, Elissa Knight, Jeff Garlin, John Ratzenberger, Kathy Najimy, with Sigourney Weaver and Fred Willard. Not getting into the plot of the film as it may ruin Shady's or anyone else's chances of ever viewing it or making harsh opinions on the film, which are and should be incorrect. 
I hope Shady will not post-pone this issue and will sort it out immedeatly after reading this issue post.
Thank you for your attention. (and have fun watching wall-e)
![Screenshot_1](https://github.com/PRISM-Servers/plugins_public/assets/158214938/1c341336-61d6-48dd-93f6-d32ec6df3c4f)
![Screenshot_2](https://github.com/PRISM-Servers/plugins_public/assets/158214938/0381425a-0a30-4c7f-b41d-f44f7b14fe14)

**Comment by SmellyFishRW** [comment]
Yes I agree shady should fix this issue ASAP.

**Comment by MikeVP05** [comment]
real

**Comment by lespygaming** [comment]
Issue resolved a few days ago :)
